### ISSUE TITLE
Error downloading image

### ISSUE THREAD

**Issue by notDavid** [flynnwasnt/macOS-Beta-Downloader#1]
Hi there, i'm getting this error. Any ideas what the cause is?

(i need the latest Big Sur public beta...)

Thanks!

```
$ python3 fetch-macOS.py --big-sur
[+] Fetching https://swscan.apple.com/content/catalogs/others/index-10.16seed-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
Traceback (most recent call last):
  File "fetch-macOS.py", line 442, in <module>
    main()
  File "fetch-macOS.py", line 405, in main
    product = products["001-26097"]
KeyError: '001-26097'
```

**Comment by notDavid** [comment]
Ah, i see it now. The new [Product ID](https://github.com/flynnwasnt/macOS-Beta-Downloader/blob/master/fetch-macOS.py#L405) for Beta6 = 001-43966

Find them here: https://mrmacintosh.com/category/11-0-big-sur-beta/
